version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: mkdir -p test-results
      - run: pytest --junitxml=test-results/junit.xml -o junit_family=legacy
      - store_test_results:
          path: test-results

workflows:
  build_and_test:
    jobs:
      - build
      - test
